//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CondSetTable
    {
        public CondSetTable()
        {
            this.RuleItemTable = new HashSet<RuleItemTable>();
        }
    
        public string Id { get; set; }
        public int CondSupCount { get; set; }
        public string CondtionsJson { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<RuleItemTable> RuleItemTable { get; set; }
    }
}
