//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edge
    {
        public Edge()
        {
            this.Obstacle = new HashSet<Obstacle>();
        }
    
        public int EdgeId { get; set; }
        public int StartId { get; set; }
        public int WayId { get; set; }
        public int EndId { get; set; }
        public double EdgeLength { get; set; }
        public double EdgeHeading { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Node Node1 { get; set; }
        public virtual Way Way { get; set; }
        public virtual ICollection<Obstacle> Obstacle { get; set; }
    }
}
