//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacebookProccesedEntries
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string Sportsman { get; set; }
        public string LikesBooks { get; set; }
        public string LikesMusic { get; set; }
        public string LikesSports { get; set; }
        public string LikesTravelling { get; set; }
        public string LikesMovies { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Category { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
