//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoursquareVenuesCategories
    {
        public FoursquareVenuesCategories()
        {
            this.FoursquareVenuesCategories1 = new HashSet<FoursquareVenuesCategories>();
        }
    
        public string Id { get; set; }
        public string Category { get; set; }
        public string Parent { get; set; }
        public int UserCategoryId { get; set; }
    
        public virtual ICollection<FoursquareVenuesCategories> FoursquareVenuesCategories1 { get; set; }
        public virtual FoursquareVenuesCategories FoursquareVenuesCategories2 { get; set; }
        public virtual UserCategory UserCategory { get; set; }
    }
}
