//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smartGPSEntities : DbContext
    {
        public smartGPSEntities()
            : base("name=smartGPSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FacebookProfile> FacebookProfile { get; set; }
        public DbSet<Profile> Profile { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserHelper> UserHelper { get; set; }
        public DbSet<NotificationCategory> NotificationCategory { get; set; }
        public DbSet<Notifications> Notifications { get; set; }
    }
}
