//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.Edge = new HashSet<Edge>();
            this.Edge1 = new HashSet<Edge>();
        }
    
        public int NodeId { get; set; }
        public double NodeLat { get; set; }
        public double NodeLong { get; set; }
        public short NodeUsed { get; set; }
    
        public virtual ICollection<Edge> Edge { get; set; }
        public virtual ICollection<Edge> Edge1 { get; set; }
    }
}
