//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obstacle
    {
        public int ObstacleId { get; set; }
        public int EdgeId { get; set; }
        public string ObstacleType { get; set; }
        public short ObstacleNoPass { get; set; }
    
        public virtual Edge Edge { get; set; }
    }
}
