//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleItemTable
    {
        public string Id { get; set; }
        public int RuleSupCount { get; set; }
        public string ClassKey { get; set; }
        public string ClassValue { get; set; }
        public int DataSize { get; set; }
        public string UserId { get; set; }
        public string CondSetId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual CondSetTable CondSetTable { get; set; }
        public virtual User User { get; set; }
    }
}
