//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public string Id { get; set; }
        public string DepartudeAddress { get; set; }
        public double DepartureLatitude { get; set; }
        public double DepartudeLongitude { get; set; }
        public string DestinationAddress { get; set; }
        public double DestinationLatitude { get; set; }
        public double DestinationLongitude { get; set; }
        public double Time { get; set; }
        public double Distance { get; set; }
        public string StatusId { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public double CurrentLatitude { get; set; }
        public double CurrentLongitude { get; set; }
        public string Directions { get; set; }
        public Nullable<int> Mode { get; set; }
    
        public virtual TravelStatusCategory TravelStatusCategory { get; set; }
        public virtual User User { get; set; }
    }
}
