//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FacebookProccesedEntries = new HashSet<FacebookProccesedEntries>();
            this.FacebookProfile = new HashSet<FacebookProfile>();
            this.FoursquareProfile = new HashSet<FoursquareProfile>();
            this.Notifications = new HashSet<Notifications>();
            this.Profile = new HashSet<Profile>();
            this.RuleItemTable = new HashSet<RuleItemTable>();
            this.Travel = new HashSet<Travel>();
            this.UserHelper = new HashSet<UserHelper>();
        }
    
        public string Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string FacebookId { get; set; }
        public string TwitterId { get; set; }
        public System.DateTime DateLastLogin { get; set; }
        public string GcmId { get; set; }
        public string FoursquareId { get; set; }
    
        public virtual ICollection<FacebookProccesedEntries> FacebookProccesedEntries { get; set; }
        public virtual ICollection<FacebookProfile> FacebookProfile { get; set; }
        public virtual ICollection<FoursquareProfile> FoursquareProfile { get; set; }
        public virtual ICollection<Notifications> Notifications { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
        public virtual ICollection<RuleItemTable> RuleItemTable { get; set; }
        public virtual ICollection<Travel> Travel { get; set; }
        public virtual ICollection<UserHelper> UserHelper { get; set; }
    }
}
