//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Way
    {
        public Way()
        {
            this.Edge = new HashSet<Edge>();
        }
    
        public int WayId { get; set; }
        public int WayTypeId { get; set; }
        public int WayMaxSpeed { get; set; }
        public short WayOneWay { get; set; }
        public string WayName { get; set; }
        public string WayRef { get; set; }
    
        public virtual ICollection<Edge> Edge { get; set; }
        public virtual WayType WayType { get; set; }
    }
}
