//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartGPS.Persistance
{
    using System;
    using System.Collections.Generic;
    
    public partial class WayType
    {
        public WayType()
        {
            this.Way = new HashSet<Way>();
        }
    
        public int WayTypeId { get; set; }
        public string WayTypeName { get; set; }
        public int WayTypeDefSpeed { get; set; }
        public int WayTypeDefSpdRes { get; set; }
    
        public virtual ICollection<Way> Way { get; set; }
    }
}
